from typing import BinaryIO, Protocol


class StorageBackend(Protocol):
    def save(self, *, storage_key: str, source: BinaryIO) -> None: ...
    def open(self, storage_key: str) -> BinaryIO: ...
    def exists(self, storage_key: str) -> bool: ...
    def delete(self, storage_key: str) -> None: ...
